klipper_repair_coupon:
    resource: '@KlipperRepairBundle/Controller/ApiCouponController.php'
    type: annotation
    prefix: '/{organization}'
    requirements:
        organization: 'user|[\w\.\-\_]+'
