nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers:
            - 'Authorization'
            - 'Content-Type'
            - 'Referer'
            - 'User-Agent'
            - 'X-Accept-Version'
            - 'X-Fields'
            - 'X-Filter'
            - 'X-Force-Delete'
            - 'X-Metadata-Details'
            - 'X-Object'
            - 'X-Objects'
            - 'X-Query'
            - 'X-Search'
            - 'X-Sort'
            - 'X-Timezone'
            - 'X-Transactional'
        expose_headers:
            - '*'
        max_age: 3600
    paths:
        '^/': null
