parameters:
    api_base_host: null
    api_base_path: '/api'

# Framework
framework:
    cache:
        pools:
            cache.app.expression:
                adapter:          cache.app
                default_lifetime: 31536000
                public:           true

# Klipper API
klipper_api:
    base_host: '%api_base_host%'
    base_path: '%api_base_path%'
    versioning:
        default_version: '1.0'
        available_versions:
            - '1.0'
