klipper_repair_coupon:
    resource: '@KlipperBuybackBundle/Controller/ApiAuditItemController.php'
    type: annotation
    prefix: '/{organization}'
    requirements:
        organization: 'user|[\w\.\-\_]+'
