klipper_routing:
    host_auto_config:
        '*/{organization}':
            defaults:
                _organizational: organization

        '*':
            requirements:
                organization: 'user|[a-zA-Z0-9\.\-\_]+'
                id: '[a-z0-9\-]+'
                '*_id': '[a-z0-9\-]+'
                ext: 'jpg|png|webp|gif'
                position: '\d+'
