# Doctrine
doctrine:
    orm:
        resolve_target_entities:
            Klipper\Module\BuybackBundle\Model\AuditConditionInterface: App\Entity\AuditCondition
            Klipper\Module\BuybackBundle\Model\AuditItemInterface: App\Entity\AuditItem
            Klipper\Module\BuybackBundle\Model\AuditBatchInterface: App\Entity\AuditBatch
            Klipper\Module\BuybackBundle\Model\AuditBatchRequestItemInterface: App\Entity\AuditBatchRequestItem
            Klipper\Module\BuybackBundle\Model\BuybackModuleInterface: App\Entity\BuybackModule
            Klipper\Module\BuybackBundle\Model\BuybackOfferInterface: App\Entity\BuybackOffer
