# Doctrine
doctrine:
    orm:
        resolve_target_entities:
            Klipper\Module\BuybackBundle\Model\AuditConditionInterface: App\Entity\AuditCondition
            Klipper\Module\BuybackBundle\Model\BuybackModuleInterface: App\Entity\BuybackModule
