# Doctrine
doctrine:
    orm:
        resolve_target_entities:
            Klipper\Module\RepairBundle\Model\BreakdownInterface: App\Entity\Breakdown
            Klipper\Module\RepairBundle\Model\RepairModuleInterface: App\Entity\RepairModule
            Klipper\Module\RepairBundle\Model\RepairModuleProductInterface: App\Entity\RepairModuleProduct
            Klipper\Module\RepairBundle\Model\RepairPlaceInterface: App\Entity\RepairPlace
            Klipper\Module\RepairBundle\Model\RepairInterface: App\Entity\Repair
            Klipper\Module\RepairBundle\Model\RepairCommentInterface: App\Entity\RepairComment
            Klipper\Module\RepairBundle\Model\RepairHistoryInterface: App\Entity\RepairHistory
            Klipper\Module\RepairBundle\Model\RepairItemInterface: App\Entity\RepairItem
            Klipper\Module\RepairBundle\Model\RepairBreakdownInterface: App\Entity\RepairBreakdown
            Klipper\Module\RepairBundle\Model\CouponInterface: App\Entity\Coupon
