# Framework
framework:
    cache:
        pools:
            cache.app.role_hierarchy:
                adapter:          cache.app
                default_lifetime: 31536000
                public:           true

# Doctrine
doctrine:
    orm:
        filters:
            sharing:
                class: Klipper\Component\Security\Doctrine\ORM\Filter\SharingFilter
                enabled: true

        resolve_target_entities:
            Symfony\Component\Security\Core\User\UserInterface: App\Entity\User
            Klipper\Component\Security\Model\UserInterface: App\Entity\User
            Klipper\Component\Security\Model\RoleInterface: App\Entity\Role
            Klipper\Component\Security\Model\GroupInterface: App\Entity\Group
            Klipper\Component\Security\Model\OrganizationInterface: App\Entity\Organization
            Klipper\Component\Security\Model\OrganizationHierarchicalInterface: App\Entity\Organization
            Klipper\Component\Security\Model\OrganizationUserInterface: App\Entity\OrganizationUser
            Klipper\Component\Security\Model\PermissionInterface: App\Entity\Permission
            Klipper\Component\Security\Model\SharingInterface: App\Entity\Sharing

# Klipper Security
klipper_security:
    host_role:
        enabled: true
    public_role:
        enabled: true
    object_filter:
        enabled: true
    role_hierarchy:
        enabled: true
        cache: cache.app.role_hierarchy
    security_voter:
        role: true
        group: true
    organizational_context:
        enabled: true
    expression:
        override_voter: true
        functions:
            is_basic_auth: true
            is_granted: true
            is_organization: true
    doctrine:
        orm:
            object_filter_voter: true
            listeners:
                permission_checker: true
                object_filter: false
                role_hierarchy: true
                private_sharing: true
                sharing_delete: true
            filters:
                sharing: true
    sharing:
        identity_types:
            App\Entity\User:
                roleable: true
                permissible: true
            App\Entity\Role:
                permissible: true
            App\Entity\Group:
                permissible: true
            App\Entity\Organization:
                permissible: true
    default_permissions:
        fields:
            id: [read]
            externalIds:
                editable: true
                operations: [read]
            createdAt: [read]
            updatedAt: [read]
        master_mapping_permissions:
            view: read
            update: edit
            create: edit
            delete: edit
    permissions:
        App\Entity\User:
            operations: [view, create, update, delete]
            fields:
                username: [read, edit]
                email: [read, edit]
                roles: [read]
        App\Entity\Organization:
            build_fields: false
            fields:
                name: [read, edit]
                label: [read, edit]
                enabled: [read]
                roles: [read]
        App\Entity\OrganizationUser:
            build_fields: false
            mapping_permissions:
                create: invite
                delete: revoke
            fields:
                enabled: [read, edit]
                roles: [read, edit]
                groups: [read, edit]
                organization: [read]
        App\Entity\Role:
            build_fields: false
            fields:
                name: [read, edit]
                label: [read, edit]
                organization: [read]
                children: [read, edit]
        App\Entity\Group:
            build_fields: false
            fields:
                name: [read, edit]
                label: [read, edit]
                organization: [read]
                roles: [read, edit]
        App\Entity\OauthClient:
            operations: [view, create, update, delete]
            build_fields: false
            fields:
                clientId: [read]
                enabled: [read, edit]
                grantTypes: [read, edit]
                label: [read, edit]
                name: [read, edit]
                redirectUri: [read, edit]
                secret: [read, edit]
