# Klipper Content
klipper_content:
    uploader:
        configurations:
            user_image:
                path: '%env(resolve:CONTENT_BASE_PATH)%/users'
                max_size: 5 Mb
                namer: uuid
            organization_image:
                path: '%env(resolve:CONTENT_BASE_PATH)%/organizations'
                max_size: 5 Mb
                namer: uuid
