# Klipper Content
klipper_content:
    uploader:
        configurations:
            user_profile_image:
                path: '%env(resolve:CONTENT_BASE_PATH)%/profiles'
                max_size: 5 Mb
                namer: uuid
