# Doctrine
doctrine:
    orm:
        resolve_target_entities:
            Klipper\Component\Portal\Model\PortalInterface: App\Entity\Portal
            Klipper\Component\Portal\Model\PortalUserInterface: App\Entity\PortalUser
