# Doctrine
doctrine:
    orm:
        resolve_target_entities:
            Klipper\Module\ProductBundle\Model\BrandInterface: App\Entity\Brand
            Klipper\Module\ProductBundle\Model\AttributeInterface: App\Entity\Attribute
            Klipper\Module\ProductBundle\Model\AttributeItemInterface: App\Entity\AttributeItem
            Klipper\Module\ProductBundle\Model\ProductInterface: App\Entity\Product
            Klipper\Module\ProductBundle\Model\ProductRangeInterface: App\Entity\ProductRange
            Klipper\Module\ProductBundle\Model\ProductSupplierInterface: App\Entity\ProductSupplier
            Klipper\Module\ProductBundle\Model\ProductCombinationInterface: App\Entity\ProductCombination
            Klipper\Module\ProductBundle\Model\PriceListInterface: App\Entity\PriceList
            Klipper\Module\ProductBundle\Model\PriceListRuleInterface: App\Entity\PriceListRule

# Klipper Content
klipper_content:
    uploader:
        configurations:
            product_image:
                path: '%env(resolve:CONTENT_BASE_PATH)%/products'
                max_size: 5 Mb
                namer: uuid
