# Services
services:
    App\Sharing\LabelBuilder\:
        resource: '../../src/Sharing/LabelBuilder'
        tags: ['klipper_security_extra.sharing_entry_label_builder']

# Doctrine
doctrine:
    orm:
        filters:
            role:
                class: Klipper\Component\SecurityExtra\Doctrine\Filter\RoleFilter
                enabled: true
            organization_only:
                class: Klipper\Component\SecurityExtra\Doctrine\Filter\OrganizationOnlyFilter
                enabled: true
            organization:
                class: Klipper\Component\SecurityExtra\Doctrine\Filter\OrganizationFilter
                enabled: true
            organizational:
                class: Klipper\Component\SecurityExtra\Doctrine\Filter\OrganizationalFilter
                enabled: true
            organization_user:
                class: Klipper\Component\SecurityExtra\Doctrine\Filter\OrganizationUserFilter
                enabled: true
            userable:
                class: Klipper\Component\SecurityExtra\Doctrine\Filter\UserableFilter
                enabled: true


# Klipper Security Extra
klipper_security_extra:
    role_filter:
        excluded_roles:
            - ROLE_SUPER_ADMIN
            - ROLE_ADMIN_PLATFORM
            - ROLE_PUBLIC

    organizational_filter:
        optional_all_filter_classes:
            - Klipper\Component\Security\Model\RoleInterface

    sharing_entries:
        App\Entity\User:
            field:             username
            repository_method: findByUserIdentifierOrHavingEmails
        App\Entity\Role:
            field:             name
            repository_method: findByNames
        App\Entity\Group:
            field:             name
            repository_method: findByNames
        App\Entity\Organization:
            field:             name
            repository_method: findByNames

    doctrine:
        orm:
            permissions:
                disable_filters:
                    - role
                    - organization_only
                    - organization
                    - organizational
                    - organization_user
                    - userable
                    - sharing
