# Doctrine
doctrine:
    orm:
        resolve_target_entities:
            Klipper\Component\SecurityOauth\Model\OauthClientInterface: App\Entity\OauthClient
            Klipper\Component\SecurityOauth\Model\OauthAccessTokenInterface: App\Entity\OauthAccessToken
            Klipper\Component\SecurityOauth\Model\OauthRefreshTokenInterface: App\Entity\OauthRefreshToken
            Klipper\Component\SecurityOauth\Model\OauthAuthCodeInterface: App\Entity\OauthAuthCode

# Klipper Security Oauth
klipper_security_oauth:
    private_key_permissions_check: false
    user_provider: users
    scopes:
        availables:
            - meta/user
            - meta/user.readonly
