klipper_device_dedevice_attachment:
    resource: '@KlipperDeviceBundle/Controller/ApiDeviceAttachmentController.php'
    type: annotation
    prefix: '/{organization}'
    requirements:
        organization: 'user|[\w\.\-\_]+'
