# Doctrine
doctrine:
    dbal:
        # Doctrine Migrations
        schema_filter: '~^(?!%env(resolve:APP_PREFIX)%_sessions)(%env(resolve:APP_PREFIX)%_)~'

        types:
            datetime: Klipper\Component\DoctrineExtensionsExtra\DBAL\Types\UtcDateTimeType
            date: Klipper\Component\DoctrineExtensionsExtra\DBAL\Types\UtcDateType
            time: Klipper\Component\DoctrineExtensionsExtra\DBAL\Types\UtcTimeType
            guid: Klipper\Component\DoctrineExtensionsExtra\DBAL\Types\GuidType
    orm:
        filters:
            expirable:
                class: Klipper\Component\DoctrineExtensionsExtra\Filter\ExpirableFilter
                enabled: true

        dql:
            datetime_functions:
                day: Klipper\Component\DoctrineExtensionsExtra\ORM\Query\AST\Functions\SimpleFunction
                month: Klipper\Component\DoctrineExtensionsExtra\ORM\Query\AST\Functions\SimpleFunction
                timestamp: Klipper\Component\DoctrineExtensionsExtra\ORM\Query\AST\Functions\SimpleFunction
                year: Klipper\Component\DoctrineExtensionsExtra\ORM\Query\AST\Functions\SimpleFunction
            string_functions:
                cast: Klipper\Component\DoctrineExtensionsExtra\ORM\Query\AST\Functions\String\Cast
                concat: Klipper\Component\DoctrineExtensionsExtra\ORM\Query\AST\Functions\String\Concat
                unaccent: Klipper\Component\DoctrineExtensionsExtra\ORM\Query\AST\Functions\String\Unaccent
                json_get: Klipper\Component\DoctrineExtensionsExtra\ORM\Query\AST\Functions\String\JsonGet
                find_in_set: Klipper\Component\DoctrineExtensionsExtra\ORM\Query\AST\Functions\String\FindInSet
            numeric_functions:
                convert_surface: Klipper\Component\DoctrineExtensionsExtra\ORM\Query\AST\Functions\Numeric\ConvertSurface

# Klipper Doctrine Extensions Extra
klipper_doctrine_extensions_extra:
    locale_fallback: '%locale_fallback%'

    orm:
        table_prefix: '%env(resolve:APP_PREFIX)%_'

        listeners:
            default:
                htmlable: true
                auto_numberable: true
