klipper_api_user_user:
    resource: '@KlipperApiUserBundle/Controller/UserController.php'
    type: annotation
    defaults:
        _priority: 500

klipper_api_user_profile:
    resource: '@KlipperApiUserBundle/Controller/ProfileController.php'
    type: annotation
    defaults:
        _priority: 500

klipper_api_user_organization:
    resource: '@KlipperApiUserBundle/Controller/OrganizationController.php'
    type: annotation
    prefix: '/{organization}'
    defaults:
        _organizational_type: org
    requirements:
        organization: '[\w\.\-\_]+'

klipper_api_user_connected_user:
    resource: '@KlipperApiUserBundle/Controller/ConnectedUserController.php'
    type: annotation
    prefix: '/{organization}'
    requirements:
        organization: 'user|[\w\.\-\_]+'
