# Doctrine
doctrine:
    orm:
        resolve_target_entities:
            Klipper\Module\DeviceBundle\Model\DeviceInterface: App\Entity\Device
            Klipper\Module\DeviceBundle\Model\DeviceAttachmentInterface: App\Entity\DeviceAttachment

klipper_content:
    uploader:
        configurations:
            device_attachment:
                path: '%env(resolve:CONTENT_BASE_PATH)%/device_attachment'
                max_size: 100 Mb
                namer: uuid
                attachment_class: App\Entity\DeviceAttachment

services:
    # Device Attachment
    app.doctrine_delete_content_config.device_attachment:
        tags: ['klipper_content.doctrine_delete_config']
        class: Klipper\Component\Content\Doctrine\DeleteContentConfig
        arguments:
            - 'device_attachment'
            - App\Entity\DeviceAttachment
            - 'filePath'

    app.uploader_name_config.device_attachment:
        tags: ['klipper_content.uploader_name_config']
        class: Klipper\Component\Content\Config\UploaderNameConfig
        arguments:
            - 'device_attachment'
            - App\Entity\DeviceAttachment
